<a href="https://colab.research.google.com/github/sidhunt/ML-implementations/blob/main/IELM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2 part 2 submission by Siddhant Badola (ID-1154586)


---
**Problem Statement:** Implement Incremental Extreme Learning Machine to deepen the understanding of the random network. 


---
**Methodology:** In this assignment we have to implement Incremental Extreme Learning Machine.We have to use two datasets, one for classification and one for regression.For classification we have to choose one of the provided dataset in assignment task.I have chosen MNIST dataset.Since this project was written in Google Colab, it already contains MNIST training and testing dataset.For regression I chose [Metro Interstate Traffic Volume Data Set](https://archive.ics.uci.edu/ml/datasets/Metro+Interstate+Traffic+Volume) . You can check out the dataset by clicking on the dataset title. It basically contains hourly data of traffic at an interstate.


---

**Result/Implementation**

I got the following results:

*   Training Accuracy:  99.9949997499875 % 
(Classification) MNIST training time: 0.7764153480529785  seconds

* Testing Accuracy 9.8009800980098 %
(Classification) MNIST testing time: 0.4259660243988037  seconds

* Training RMSE:  0.006454972243679028
(Regression) UCI training time: 0.6194558143615723  seconds

* Testing RMSE 0.4998821508572355
(Regression) UCI testing time: 0.6644558906555176  seconds

Provided below is the complete workflow:-


We load the MNIST dataset first from sample training and testing data in Google Colab.We also convert them from csv to numpy.

In [ ]:
mnist_data_train=pd.read_csv("sample_data/mnist_train_small.csv")
mnist_data_test=pd.read_csv("sample_data/mnist_test.csv")
d1=mnist_data_train.to_numpy()
d2=mnist_data_test.to_numpy()
print(d1.shape)
print(d2.shape)
print(d1)

(19999, 785)
(9999, 785)
[[5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]


We first check the output labels in training data.

In [ ]:
print(d1[0:19999,0:1])

[[5]
 [7]
 [9]
 ...
 [2]
 [9]
 [5]]


We then check the input data in training data.

In [ ]:
print(d1[0:19999,1:795])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


On checking the dimensions we can see the data contains almost 20000 samples and 785 attributes.

In [ ]:
d1=d1/255
print(d1.shape)

(19999, 785)


We then upload the Metro Interstate Traffic Volume dataset.

In [ ]:
from google.colab import files
files.upload()

Saving Metro_Interstate_Traffic_Volume.csv to Metro_Interstate_Traffic_Volume.csv


{'Metro_Interstate_Traffic_Volume.csv': b'holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume\r\nNone,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545\r\nNone,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516\r\nNone,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767\r\nNone,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026\r\nNone,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918\r\nNone,291.72,0.0,0.0,1,Clear,sky is clear,2012-10-02 14:00:00,5181\r\nNone,293.17,0.0,0.0,1,Clear,sky is clear,2012-10-02 15:00:00,5584\r\nNone,293.86,0.0,0.0,1,Clear,sky is clear,2012-10-02 16:00:00,6015\r\nNone,294.14,0.0,0.0,20,Clouds,few clouds,2012-10-02 17:00:00,5791\r\nNone,293.1,0.0,0.0,20,Clouds,few clouds,2012-10-02 18:00:00,4770\r\nNone,290.97,0.0,0.0,20,Clouds,few clouds,2012-10-02 19:00:00,3539\r\nNone,289.38,0.0,0.0,1,Clear,sky is clear,2012-10-02 20:00:00,2784\r\nNone,288

The dataset contains non-numeric attributes but we are only concerned with numeric attributes so we seperate them and convert them into a new numpy array.**We also split the dataset into separate training and testing dataset.**Also we replace "nan" or missing values with 0.

In [ ]:
abc= pd.read_csv("Metro_Interstate_Traffic_Volume.csv")
abc.head()
abc1=pd.DataFrame(abc,columns=["temp","rain_1h","snow_1h","clouds_all","traffic_volume"])
traffic=abc1.to_numpy()
print(traffic.shape)
traffic_train=traffic[0:24000]
traffic_test=traffic[24001:48204]
print(traffic_test.shape,traffic_train.shape)
print(traffic_train)
np.nan_to_num(traffic_train)

(48204, 5)
(24203, 5) (24000, 5)
[[ 288.28    0.      0.     40.   5545.  ]
 [ 289.36    0.      0.     75.   4516.  ]
 [ 289.58    0.      0.     90.   4767.  ]
 ...
 [ 293.      0.      0.     40.   3377.  ]
 [ 291.98    0.      0.     40.   2784.  ]
 [ 290.47    0.      0.     20.   2654.  ]]


array([[ 288.28,    0.  ,    0.  ,   40.  , 5545.  ],
       [ 289.36,    0.  ,    0.  ,   75.  , 4516.  ],
       [ 289.58,    0.  ,    0.  ,   90.  , 4767.  ],
       ...,
       [ 293.  ,    0.  ,    0.  ,   40.  , 3377.  ],
       [ 291.98,    0.  ,    0.  ,   40.  , 2784.  ],
       [ 290.47,    0.  ,    0.  ,   20.  , 2654.  ]])

This is our final training data.

In [ ]:
print(traffic_train[0:24000,0:5])

[[ 288.28    0.      0.     40.   5545.  ]
 [ 289.36    0.      0.     75.   4516.  ]
 [ 289.58    0.      0.     90.   4767.  ]
 ...
 [ 293.      0.      0.     40.   3377.  ]
 [ 291.98    0.      0.     40.   2784.  ]
 [ 290.47    0.      0.     20.   2654.  ]]


We then code the regression training and testing functions.

In [ ]:
def trainRegressionUCI(train_input_data,outputLabel):  
    outputLabel = sig(outputLabel)
    lmax = 20
    E = outputLabel
    l = 0
    defError = 0.1 
    for l in range(1,lmax):
        hMat = np.zeros(shape = (train_input_data.shape[0],l))
        for row in train_input_data:
           k=0
           row = np.reshape(row, (1,np.product(row.shape)))
           h = []
           for i in range(l):
               weights = np.random.random((train_input_data.shape[1],1))
               output = predVal(row,weights) 
               h.append(output)   
           h = np.reshape(h, (-1, l))  
           hMat[k] = h[0]
           k = k + 1
        beta = np.dot(np.linalg.pinv(hMat), outputLabel)
        E = E - np.dot(hMat,beta)
        E_VAL = math.sqrt( np.square(np.subtract(outputLabel,E)).mean() )
        if(E_VAL < defError) :
            print("Training RMSE: ",E_VAL)
            break 
    return beta

def testRegressionUCI(data, outputD,b):
    outputD =sig(outputD)
    la = b.shape[0]
    hMat = np.zeros(shape = (data.shape[0],la))
    for row in data:
       k=0
       row = np.reshape(row, (1,np.product(row.shape)))
       h = []
       for i in range(la):
           weights = np.random.random((data.shape[1],1))
           output = predVal(row,weights)
           h.append(output)
       h = np.reshape(h, (-1, la))  
       hMat[k] = h[0]
       k = k + 1 
    o = sig(np.dot(hMat , b))
    rmse =  math.sqrt( np.square(np.subtract(outputD,o)).mean() )
    print("Testing RMSE",rmse)


We now import the respective libraries and code the MNIST classification training and testing functions. We finally get the following outputs:-


*   Training Accuracy:  99.9949997499875 % 
(Classification) MNIST training time: 0.7764153480529785  seconds

* Testing Accuracy 9.8009800980098 %
(Classification) MNIST testing time: 0.4259660243988037  seconds

* Training RMSE:  0.006454972243679028
(Regression) UCI training time: 0.6194558143615723  seconds

* Testing RMSE 0.4998821508572355
(Regression) UCI testing time: 0.6644558906555176  seconds




In [ ]:
import numpy as np
import pandas as pd
import math
import time as t
b = 0.01
def predVal(inputs,w):
    inputs = inputs.astype(float)
    output = relu(np.dot(inputs, w) + b) 
    return output

def sig(x):
    calculate = 1/(1+np.exp(-x))
    return calculate

def relu(x):
    cal = np.maximum(x, 0)
    return cal

def predAcc(originalLabel,predicted):
        matched = 0
        for i in range(len(originalLabel)):
                if originalLabel[i] == predicted[i]:
                    matched += 1
        accuracyVal = matched / float(len(originalLabel))      
        return accuracyVal

def trainClassificationMNIST(train_input_data,outputLabel):  
    
    lmax = 20
    E = outputLabel
    l = 0
    Acc = 0.999
    for l in range(1,lmax):
        hMat = np.zeros(shape = (train_input_data.shape[0],l))
        for row in train_input_data:
           k=0
           row = np.reshape(row, (1,np.product(row.shape)))
           h = []
           for i in range(l):
               weights = np.random.random((train_input_data.shape[1],1))
               output = predVal(row,weights)
               h.append(output)
           h = np.reshape(h, (-1, l))  
           hMat[k] = h[0]
           k = k + 1
        beta = np.dot(np.linalg.pinv(hMat), outputLabel)
        E = E - np.dot(hMat,beta)
        E = relu(E)
        E_VALC = predAcc(outputLabel,E)
        if(E_VALC > Acc) :
            print("Training Accuracy: ",E_VALC*100,"%")
            break
    return beta

def testClassificationMNIST(data, outputD,b):
    la = b.shape[0]
    hMat = np.zeros(shape = (9999,la))
    for row in data:
       k=0
       row = np.reshape(row, (1,np.product(row.shape)))
       h = []
       for i in range(la):
           weights = np.random.random((784,1))
           output = predVal(row,weights)
           h.append(output)
       h = np.reshape(h, (-1, la)) 
       hMat[k] = h[0]
       k = k + 1  
    o = relu(np.dot(hMat , b))
    acc = predAcc(outputD, o)
    print("Testing Accuracy",acc*100,"%")    

#-----------------------------------------------Classification-----------------------------------------------
start=t.time()
b123=trainClassificationMNIST(d1[0:19999,1:785],d1[0:19999,0:1])
end=t.time()
print("(Classification) MNIST training time:",end-start," seconds\n")
start=t.time()
testClassificationMNIST(d2[0:9999,1:785],d2[0:9999,0:1],b123)
end=t.time()
print("(Classification) MNIST testing time:",end-start," seconds\n")
#------------------------------------------------Regression---------------------------------------------------
start=t.time()
beta123=trainRegressionUCI(traffic_train[0:24000,0:4],traffic_train[0:24000,4:5])
end=t.time()
print("(Regression) UCI training time:",end-start," seconds\n")
start=t.time()
testRegressionUCI(traffic_test[0:24203,0:4],traffic_test[0:24203,4:5],beta123)
end=t.time()
print("(Regression) UCI testing time:",end-start," seconds\n")

Training Accuracy:  99.9949997499875 %
(Classification) MNIST training time: 0.7764153480529785  seconds

Testing Accuracy 9.8009800980098 %
(Classification) MNIST testing time: 0.4259660243988037  seconds

Training RMSE:  0.006454972243679028
(Regression) UCI training time: 0.6194558143615723  seconds

Testing RMSE 0.4998821508572355
(Regression) UCI testing time: 0.6644558906555176  seconds

